### PR TITLE
Now really works

### PR DESCRIPTION
**Pull request by jiyuuchc**
Fix the problem that the plugin won't run under Fiji (only in vscode).

This patch is now tested with Fiji-linux64, from the GUI.

There is also significant code clean ups.

There is some remaining issues:

 - The configuration GUI is very ugly now after removing some of the unused parameters.
 - The plugin uses protobuf 3.24, which conflict with some other Fiji plugins, which uses an earlier version. I have to replace these libs (jars/proto-google-*), with the newer version. This probably broken some other plugins -- don't know which one.
 - Trackmate works best if the detection gives scores for each detection. Right now the score output is not transferred to trackmate.

### CODE REVIEW

**Comment by jiyuuchc** [comment]
Nick,

At this point there is very little original code left. It seems reasonable to break from the original and create a new repo -- what do you think?

Ji

________________________________________

**Comment by Nick-Kuang** [comment]
That's a good idea. I think it is also the time to move it to your github repo instead of mine. I think its pretty funny how you are doing the pull requests and I am one accepting it haha

**Comment by jiyuuchc** [comment]
Actually it is nice to have you maintaining the codebase. Save me some tracking work.

In fact I just submitted my last planned patch and I will stop working on this from now on for a while.  I'd appreciate if you can keep tracking the issues and bug fixes.

Ji

________________________________________

**Comment by Nick-Kuang** [comment]
Ok; I will send  the request to separate from the original repo

**Comment by jiyuuchc** [comment]
What request? You don't need upstream approval for a new repo.

Ji

________________________________________

**Comment by Nick-Kuang** [comment]
Oh, I meant request to GitHub support to just remove  the previous repo dependency

**Comment by jiyuuchc** [comment]
I didn't know too much about github. I assume you can simply delete the current repo and create a new one with a fresh commit. We will lose the current commit history but that doesn't matter that much with such a small project.

Ji

________________________________________

**Pull request merged**
